### ISSUE TITLE
kinfit_importVoxelstats - too many outputs

### ISSUE THREAD

**Issue by VeraKer** [cselenyi/solenabugs#16]
Because of post-hoc exploratory analysis, I have added an additional processing block at the end of my standard Solena pipeline, to keep it transparent what part of the pipeline is main analysis and what was added later for exploratory analysis. I added this block based on earlier help of Zsolt. It looks like this:
![2020_solena_bugreport_additional_block](https://user-images.githubusercontent.com/46931135/77899833-6dfd0b80-727d-11ea-95c7-50f8235ef9bc.png)

However, the last command kinfit_importVoxelstats gives the following error, repeatedly for every subject:

![2020_solena_bugreport_additional_block2](https://user-images.githubusercontent.com/46931135/77899842-71909280-727d-11ea-9d9f-71c09c05511d.png)

When I look in the folder structure, the output file has been created.
When I google the problem "Most likely cause is missing [] around left hand side that has a comma separated list expansion." the solutions given I cannot use (or would not know how to).

What could a solution be?
@cselenyi 

If I need to add additional information, let me know.

**Comment by cselenyi** [comment]
@VeraKer could you please provide the worker version (you could give the "milestone" belonging to the worker version that you used, btw..). Perhaps you could email me the kinfit file from the subject (1_kinfitresults_aal_main.mat). As a pipeline layout style comment I would suggest to leave the end part of the kinfitresults constant, it may be assumed here and there that that should be the name ending: e.g. ..._aal_main_kinfitresults.mat. But the issue reported here is not due to that :-)

**Comment by cselenyi** [comment]
@VeraKer well, at first view it appears that you are trying to use "CER_FS" as the reference region but it does not exist in the provided 1_kinfitresults_aal_main.mat file. Are you sure it's there? The layout seems to refer to "AAL main regions" so perhaps you wanted to use "CER" instead?
