### ISSUE TITLE
recon-all

### ISSUE THREAD

**Issue by ToveFrei** [cselenyi/solenabugs#2]
I thought I should get this github up and running!
I have an error when I run freesurfer on Solena. For all subjects I get the same error message:

"There was some error running recon-all that could not be handled automatically."

Is it a Solena bug?
![solena error](https://user-images.githubusercontent.com/47004823/51805969-3ad37c80-2274-11e9-90ae-d5d01e413d78.png)

**Comment by VeraKer** [comment]
First, try the solution below - following it step by step. And if it doesn't work, please say so and post the error report again.

**Issue:**
Problem with freesurfer has been that it tries to create a few file symbolic links (=sort of file “referrals”) during processing but this gives problems when running freesurfer from a Docker container from Windows as we do from Solena.
Zsolt has therefore changed/updated the freesurfer Docker ‘image’ (& container) to make freesurfer processing create file copies instead of symbolic links.
So what needs to be done, is to download his updated, fixed freesurfer Docker image (fixed version 1.0 image) to replace the old v. 1.0 image.

**To do:**
1. Open the ‘command line’ or 'command prompt' (program).
2. Enter `docker stop fsfsl`	(stops the fsfsl Docker container).
3. Enter `docker rm fsfsl`  		(removes the fsfsl Docker container).
4. Enter `docker pull kipet/fsfsl:1.0` 	(downloads, "pulls" the fixed freesurfer v. 1.0 Docker image from the Docker central storage on the Web, i.e. the Docker Hub).
5. Check that the fixed freesurfer image is present locally by entering: `docker images`. You see that there are now two images listed for which the **repository** name is _kipet/fsfsl_. One with the **tag** _1.0_ and one "ghost" image with the **tag** _\<none\>_. The _1.0_ is the new, fixed downloaded image, the _\<none\>_ image is the old, buggy one.
6. Now the ghost image needs to be removed. Write `docker rmi <image ID>` where _\<image ID\>_ should be actually the code displayed in the line of the ghost image from the previous listing. It is most likely _cbfb869e967_, so the exact command to enter would be `docker rmi cbfb869e967`. Note `rmi` means: "remove image". Also note: the reason why you should not remove the old image before downloading the new one is that they share a lot of their contents (Docker images are like lego toys built up of several smaller pieces, referred to as "layers") so deleting the old one will completely wipe out all the pieces on your machine and will force Docker to download all those shared pieces anew to have the complete new, fixed image (13.3 GB!).

Here's a screenshot showing what the `docker images` output would be before the above steps as well as steps 4-6 in action (image ID numbers might be different though):

![temp_to_github](https://user-images.githubusercontent.com/46931135/51913851-c7e31680-23d7-11e9-9b4b-0260364a866c.png)

@cselenyi 
@ToveFrei

**Comment by ToveFrei** [comment]
@VeraKer I have done all those steps and added a new Docker image and removed the old one, but the problem still occurs.

@cselenyi

**Comment by VeraKer** [comment]
@ToveFrei 
I don't know what another solution would be. 

I will add to this that I also get your error message 1 out of 8 times I run Freesurfer in Solena (the other 7/8 run without a problem), and I have not figured out yet why.

A theory I have is that the error occurs when I am running Freesurfer parallel to other command blocks for other subjects. It seems that if I only have one Freesurfer for one subject running (and nothing else in Solena) the majority of the time Freesurfer runs perfectly. This might be coincidence. 
Or perhaps the error happens when several people are using Freesurfer at the same time? 
@cselenyi 

To add to this, I post this morning's error message I got, which gives more information on what might lie behind the recon-all error. 
I have been searching where to include the -notal-check flag, but not been successful yet.

![temp_to_github_reconall](https://user-images.githubusercontent.com/46931135/51989444-5bcfe380-24a7-11e9-8a59-3fdd2b4b722b.png)

**Comment by ToveFrei** [comment]
I think we have diagnosed the issue. There seems to be an issue when more then one person tries running freesurfer in Solena at the same time. Vera got an error at 11 am this morning when I started running one subject, and I got the same error at 14:46 pm when Vera started running Freesurfer in solena on one of her subjects. 
@cselenyi

**Comment by mathesong** [comment]
This suggests that FreeSurfer is running on the omniflux server, and not on the docker container.  Is this the case @cselenyi ?  If so, is it possible to run `recon all` within the FreeSurfer docker container locally as a workaround?

**Comment by cselenyi** [comment]
@ToveFrei, @mathesong, @VeraKer 
Well, Freesurfer **is** running locally from a Docker container so there cannot be a "collision" between different people running it on different computers. (You can actually see in Vera's screenshot how it refers to "Linux … boot2docker" "computer" running Freesurfer, and that's the VirtualBox virtual Linux machine running Docker service running the fsfsl Docker container running Freesurfer :-) ).
Right now Freesurfer Docker is set up to only run 1 subject from Solena since it is resource heavy. 

Actually one of the problems could be that the VirtualBox Docker machine called "default" may have insufficient hardware resources allocated, namely memory and perhaps CPU power. I have updated the "StepsToInstallDocker.docx" document (found on ecat7_nfs shared drive in downloads/Docker) to explain how to increase available hardware resources, please see step 1./b./iv. therein.

And the error in the screenshot shared by Vera actually indicates that it is a failure of the Talairach quality check in Freesurfer. Theoretically that should be automatically handled by "freesurfMR" but the reason it failed is that Freesurfer v. 6.0.0 (i.e. the one used now) has a different error message for this issue then Freesurfer 5.3.0 used to have (the one I originally used to build the core part of "freesurfMR"). In the old one the failure message was:
`ERROR: Talairach QA check failed!`
In the current Freesurfer version it is:
`ERROR: Talairach failed!`
Accordingly, the semi-automatic fix by "freesurfMR" (which allows the user to manually, with visual inspection in SPM viewer, fix talairach.xfm and then it reruns Freesurfer with the no Talairach check, i.e. the -notal-check option) was never activated. **I am going to fix the "freesurfMR" script and create a new solena worker.**

**Comment by ToveFrei** [comment]
The above issues seemed to be fixed. I was able to successfully run 10 subjects. However, since yesterday I've gotten the same error message for all subjects:

![skarmavbild 2019-02-14 kl 07 19 09](https://user-images.githubusercontent.com/47004823/52815581-57a6e700-309f-11e9-925b-4ccb0a9fdae5.png)

@VeraKer are you getting the same error? @cselenyi was there a change in Solena yesterday?

**Comment by mathesong** [comment]
That looks like the docker container itself isn't starting up for some reason. So it doesn't appear to be pipeline-related. Have you tried restarting your PC?

**Comment by ToveFrei** [comment]
Thank you @mathesong! Problem solved when opening the docker. I've now been able to run all my subjects with fs in Solena! :)

**Comment by cselenyi** [comment]
OK, so this item is closed (for now).
