### ISSUE TITLE
New worker solena_worker_202308181224

### ISSUE THREAD

**Issue by cselenyi** [cselenyi/solenabugs#31]
### New worker version `solena_worker_202308181224`

  For the first time, the worker executable was compiled on MATLAB R2022b! This means that in order to run it the MATLAB compiler runtime (MCR) for version R2022b must be first installed (full MATLAB R2022b may also work). However, Solena itself must still be started from MATLAB R2014b, only the external worker process will be "in R2022b", so to say. The MCR installer can be found at: `\\193.10.16.204\matlab\installers\MATLAB_Runtime_R2022b_Update_5_win64.zip`.
  Additional functionality (they comes to mind): LEO (Solena command `doLEO`) and LEA (Solena command `doLEA`). Please read the Solena documentation on how to use them. If you also want to use them from the MATLAB command prompt then add the following folders to the MATLAB toolbox path (**make sure that you add them through the drive letter which maps to `\\193.10.16.204\matlab\`, e.g. `X:\`**):
`\\193.10.16.204\matlab\toolbox\m-files\LEO`
`\\193.10.16.204\matlab\toolbox\m-files\LEA`
`\\193.10.16.204\matlab\toolbox\m-files\QuEST`

  **Disclaimer**: a large set of Solena commands was validated to run in the new, R2022b-based worker. Still, please watch out for possible mismatches, bugs, etc. and let me know if something's fishy!

**Comment by GinaGriffioen** [comment]
I have an issue with WAPI. Not sure this has to do with the new worker though
Here is the command from my study layout:

Block	Parametric Imaging (WAPI!)
	{
		PET
		{
			wapi	pet1_realigned.v	1_kinfitresults.mat	16	3	1_wapist	10	REFNAME	CSO	TARGETMASKNAME	WB	TARGETMASKPADDING	2	OBTAINSE	0

It starts running, but it seems to get stuck. The Output of Worker 1 is: 
"Runner working process: solena_worker_202308181224 (status: exited without error, reserved for: Subject ashm executing block 13, command 1 [wapi])"

Command Standard Output is this:
(...)

Inverting result back to normal space...Translation independent trimmed decomposition structure detected.                                                                                                                                                            
Calling idwt3z_xlow_mx                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                     
--------------------------------------------------------------------------------                                                                                                                                                                                     
             Access violation detected at 2023-09-08 10:06:17 +0200                                                                                                                                                                                                  
--------------------------------------------------------------------------------                                                                                                                                                                                     
                                                                                                                                                                                                                                                                     
Configuration:                                                                                                                                                                                                                                                       
  Crash Decoding           : Disabled - No sandbox or build area path                                                                                                                                                                                                
  Crash Mode               : continue (default)                                                                                                                                                                                                                      
  Default Encoding         : UTF-8                                                                                                                                                                                                                                   
  Deployed                 : true                                                                                                                                                                                                                                    
  Graphics Driver          : Uninitialized hardware                                                                                                                                                                                                                  
  Graphics card 1          : Intel Corporation ( 0x8086 ) Intel(R) UHD Graphics 630 Version 31.0.101.2114 (2022-8-24)                                                                                                                                                
  Java Version             : Java 1.8.0_202-b08 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode                                                                                                                                                 
  MATLAB Architecture      : win64                                                                                                                                                                                                                                   
  MATLAB Entitlement ID    : Unknown                                                                                                                                                                                                                                 
  MATLAB Root              : C:\Program Files\MATLAB\MATLAB Runtime\R2022b                                                                                                                                                                                           
  MATLAB Version           : 9.13.0.2193358 (R2022b) Update 5                                                                                                                                                                                                        
  OpenGL                   : hardware                                                                                                                                                                                                                                
  Operating System         : Microsoft Windows 10 Pro                                                                                                                                                                                                                
  Process ID               : 19264                                                                                                                                                                                                                                   
  Processor ID             : x86 Family 6 Model 158 Stepping 10, GenuineIntel                                                                                                                                                                                        
  Session Key              : 35262507-98e6-4af8-a861-4c9d8620f507                                                                                                                                                                                                    
  Window System            : Version 10.0 (Build 19045)                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                     
Fault Count: 1                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                     
Abnormal termination:                                                                                                                                                                                                                                                
Access violation                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                     
Current Thread: 'MCR 0 interpreter thread' id 7204                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                     
Register State (from fault):                                                                                                                                                                                                                                         
  RAX = 0000000fffffffe0  RBX = 000001e66a455d20                                                                                                                                                                                                                     
  RCX = 00007ff97c3e0aa9  RDX = 000001e64aadeb40                                                                                                                                                                                                                     
  RSP = 000000531bff7a68  RBP = 000001e64b8c6350                                                                                                                                                                                                                     
  RSI = 000001e67481d400  RDI = 0000000000000008                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                     
   R8 = 000001e64b8c6358   R9 = 000001e66a456b00                                                                                                                                                                                                                     
  R10 = 000000531bff7a80  R11 = 000000531bff7b10                                                                                                                                                                                                                     
  R12 = 000001e64b8c6350  R13 = 000001e64b8c6368                                                                                                                                                                                                                     
  R14 = 000001e64629d1c0  R15 = 0000000000000000                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                     
  RIP = 00007ff97c38e18f  EFL = 00010202                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                     
   CS = 0033   FS = 0053   GS = 002b                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                     
Stack Trace (from fault):                                                                                                                                                                                                                                            
[  0] 0x00007ff97c38e18f C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\libmx.dll+02417039 matrix::detail::noninlined::mx_array_api::mxIsContainer+00000015                                                                                                 
[  1] 0x00007ff97c16bbd8 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\libmx.dll+00179160 matrix::destroyArray+00000168                                                                                                                                    
[  2] 0x00007ff9743adcc2 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\libmwlxetypes.dll+00253122 MathWorks::lxe::NewConstantXList+00003474                                                                                                                
[  3] 0x00007ff9743a9afc C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\libmwlxetypes.dll+00236284 MathWorks::lxe::AddTypeToTuple+00001164                                                                                                                  
[  4] 0x00007ff974c4849a C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_lxe.dll+02917530 MathWorks::lxe::LXEConstants::IsIfElse+00525994                                                                                                                  
[  5] 0x00007ff974c4ca14 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_lxe.dll+02935316 MathWorks::lxe::LXEConstants::IsY+00012980                                                                                                                       
[  6] 0x00007ff974c49e61 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_lxe.dll+02924129 MathWorks::lxe::LXEConstants::IsY+00001793                                                                                                                       
[  7] 0x00007ff974c4db55 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_lxe.dll+02939733 MathWorks::lxe::LXEConstants::IsY+00017397                                                                                                                       
[  8] 0x00007ff974c4de03 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_lxe.dll+02940419 MathWorks::lxe::LXEConstants::IsY+00018083                                                                                                                       
[  9] 0x00007ff974c4d758 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_lxe.dll+02938712 MathWorks::lxe::LXEConstants::IsY+00016376                                                                                                                       
[ 10] 0x00007ff974c49606 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_lxe.dll+02921990 MathWorks::lxe::LxeTypes::GetTypeXvalueOf+00000598                                                                                                               
[ 11] 0x00007ff974d17303 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_lxe.dll+03764995 MathWorks::lxe::SetEngineImplUnlinkFlagForAllCallsOnStack+00042979                                                                                               
[ 12] 0x00007ff974d1ae10 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_lxe.dll+03780112 MathWorks::lxe::SetEngineImplUnlinkFlagForAllCallsOnStack+00058096                                                                                               
[ 13] 0x00007ff979b74a90 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\libmwlxemainservices.dll+01198736 FeatureTestObservableWorkspace+00184240                                                                                                           
[ 14] 0x00007ff979ade776 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\libmwlxemainservices.dll+00583542 mwboost::archive::detail::pointer_oserializer<mwboost::archive::xml_oarchive,MathWorks::lxe::PreLineExecutionEvent>::save_object_ptr+00069206     
[ 15] 0x00007ff979ae018f C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\libmwlxemainservices.dll+00590223 mwboost::archive::detail::pointer_oserializer<mwboost::archive::xml_oarchive,MathWorks::lxe::PreLineExecutionEvent>::save_object_ptr+00075887     
[ 16] 0x00007ff979b58d07 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\libmwlxemainservices.dll+01084679 FeatureTestObservableWorkspace+00070183                                                                                                           
[ 17] 0x00007ff979b58913 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\libmwlxemainservices.dll+01083667 FeatureTestObservableWorkspace+00069171                                                                                                           
[ 18] 0x00007ff97b42adde C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_interpreter.dll+00634334 inEvalIn+00000062                                                                                                                                        
[ 19] 0x00007ff9665c0c9f C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\builtins\m_interpreter\mwm_interpreter_builtinimpl.dll+00199839 us_set_bundle_context_instance_com_mathworks_m_interpreter_builtinimpl+00164175                                     
[ 20] 0x00007ff966598d02 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\builtins\m_interpreter\mwm_interpreter_builtinimpl.dll+00036098 us_set_bundle_context_instance_com_mathworks_m_interpreter_builtinimpl+00000434                                     
[ 21] 0x00007ff977886476 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\builtin.dll+00156790 MathWorks::builtin::BuiltinFcn::invoke+00001174                                                                                                                
[ 22] 0x00007ff979cf8494 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_dispatcher.dll+00361620 mdLoadModuleForPackageOrClass+00007524                                                                                                                    
[ 23] 0x00007ff979cf8625 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_dispatcher.dll+00362021 mdLoadModuleForPackageOrClass+00007925                                                                                                                    
[ 24] 0x00007ff979cab76e C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_dispatcher.dll+00046958                                                                                                                                                           
[ 25] 0x00007ff979ccd1ad C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_dispatcher.dll+00184749 Mfh_MATLAB_fn_impl::dispatch+00000045                                                                                                                     
[ 26] 0x00007ff979aa0c74 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\libmwlxemainservices.dll+00330868 mwboost::archive::codecvt_null<wchar_t>::do_max_length+00234740                                                                                   
[ 27] 0x00007ff979aaf1f0 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\libmwlxemainservices.dll+00389616 mwboost::archive::codecvt_null<wchar_t>::do_max_length+00293488                                                                                   
[ 28] 0x00007ff974ef22a1 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_lxe.dll+05710497 MathWorks::lxe::ReadOnlyXvaluePtr::operator=+00006049                                                                                                            
[ 29] 0x00007ff974ef3899 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_lxe.dll+05716121 MathWorks::lxe::ReadOnlyXvaluePtr::operator=+00011673                                                                                                            
[ 30] 0x00007ff974e3e4a8 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_lxe.dll+04973736 MathWorks::lxe::printLxeProfStatsForFeature+00300760                                                                                                             
[ 31] 0x00007ff974e584f9 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_lxe.dll+05080313 MathWorks::lxe::printLxeProfStatsForFeature+00407337                                                                                                             
[ 32] 0x00007ff974c4840b C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_lxe.dll+02917387 MathWorks::lxe::LXEConstants::IsIfElse+00525851                                                                                                                  
[ 33] 0x00007ff974c4ca14 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_lxe.dll+02935316 MathWorks::lxe::LXEConstants::IsY+00012980                                                                                                                       
[ 34] 0x00007ff974c49e61 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_lxe.dll+02924129 MathWorks::lxe::LXEConstants::IsY+00001793                                                                                                                       
[ 35] 0x00007ff974c4db55 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_lxe.dll+02939733 MathWorks::lxe::LXEConstants::IsY+00017397                                                                                                                       
[ 36] 0x00007ff974c4de03 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_lxe.dll+02940419 MathWorks::lxe::LXEConstants::IsY+00018083                                                                                                                       
[ 37] 0x00007ff974c4d758 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_lxe.dll+02938712 MathWorks::lxe::LXEConstants::IsY+00016376                                                                                                                       
[ 38] 0x00007ff974c49606 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_lxe.dll+02921990 MathWorks::lxe::LxeTypes::GetTypeXvalueOf+00000598                                                                                                               
[ 39] 0x00007ff974d17303 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_lxe.dll+03764995 MathWorks::lxe::SetEngineImplUnlinkFlagForAllCallsOnStack+00042979                                                                                               
[ 40] 0x00007ff974d1ae10 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_lxe.dll+03780112 MathWorks::lxe::SetEngineImplUnlinkFlagForAllCallsOnStack+00058096                                                                                               
[ 41] 0x00007ff979b74a90 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\libmwlxemainservices.dll+01198736 FeatureTestObservableWorkspace+00184240                                                                                                           
[ 42] 0x00007ff979ade776 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\libmwlxemainservices.dll+00583542 mwboost::archive::detail::pointer_oserializer<mwboost::archive::xml_oarchive,MathWorks::lxe::PreLineExecutionEvent>::save_object_ptr+00069206     
[ 43] 0x00007ff979ae018f C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\libmwlxemainservices.dll+00590223 mwboost::archive::detail::pointer_oserializer<mwboost::archive::xml_oarchive,MathWorks::lxe::PreLineExecutionEvent>::save_object_ptr+00075887     
[ 44] 0x00007ff979b3ecb3 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\libmwlxemainservices.dll+00978099 mwboost::archive::detail::iserializer<mwboost::archive::text_iarchive,MathWorks::MatlabComponents::ComponentIdentifier>::load_object_data+00303411
[ 45] 0x00007ff979b40df7 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\libmwlxemainservices.dll+00986615 mwboost::archive::detail::iserializer<mwboost::archive::text_iarchive,MathWorks::MatlabComponents::ComponentIdentifier>::load_object_data+00311927
[ 46] 0x00007ff979b3fd4c C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\libmwlxemainservices.dll+00982348 mwboost::archive::detail::iserializer<mwboost::archive::text_iarchive,MathWorks::MatlabComponents::ComponentIdentifier>::load_object_data+00307660
[ 47] 0x00007ff97b4858cb C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_interpreter.dll+01005771 inMexEvalStringWithTrap+00001547                                                                                                                         
[ 48] 0x00007ff95cbb333e \\193.10.16.204\matlab\toolbox\m-files\solena\bin\solena_worker_202308181224_mcr\solena_worke\mexEvalinBase.mexw64+00013118 mexFunction+00001550                                                                                            
[ 49] 0x00007ff97a699149 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\libmex.dll+00561481 mexfile::Inspector::needs_upgrade+00027273                                                                                                                      
[ 50] 0x00007ff97a69cb32 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\libmex.dll+00576306 MexRetrieveVersion+00011746                                                                                                                                     
[ 51] 0x00007ff97a69cca7 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\libmex.dll+00576679 MexRetrieveVersion+00012119                                                                                                                                     
[ 52] 0x00007ff97a69ce57 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\libmex.dll+00577111 MexRetrieveVersion+00012551                                                                                                                                     
[ 53] 0x00007ff97a67b10e C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\libmex.dll+00438542 mexUnlock+00017022                                                                                                                                              
[ 54] 0x00007ff979d9da32 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_dispatcher.dll+01038898 Mfh_file::dispatch_file_common+00000178                                                                                                                   
[ 55] 0x00007ff979d9cd02 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_dispatcher.dll+01035522 Mfh_error::lookup+00012722                                                                                                                                
[ 56] 0x00007ff979d9d96d C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_dispatcher.dll+01038701 Mfh_file::dispatch+00000045                                                                                                                               
[ 57] 0x00007ff979aa0c74 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\libmwlxemainservices.dll+00330868 mwboost::archive::codecvt_null<wchar_t>::do_max_length+00234740                                                                                   
[ 58] 0x00007ff979aaf1f0 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\libmwlxemainservices.dll+00389616 mwboost::archive::codecvt_null<wchar_t>::do_max_length+00293488                                                                                   
[ 59] 0x00007ff974ef22a1 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_lxe.dll+05710497 MathWorks::lxe::ReadOnlyXvaluePtr::operator=+00006049                                                                                                            
[ 60] 0x00007ff974ef4078 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_lxe.dll+05718136 MathWorks::lxe::ReadOnlyXvaluePtr::operator=+00013688                                                                                                            
[ 61] 0x00007ff974e3e4a8 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_lxe.dll+04973736 MathWorks::lxe::printLxeProfStatsForFeature+00300760                                                                                                             
[ 62] 0x00007ff974e58909 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_lxe.dll+05081353 MathWorks::lxe::printLxeProfStatsForFeature+00408377                                                                                                             
[ 63] 0x00007ff974c4840b C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_lxe.dll+02917387 MathWorks::lxe::LXEConstants::IsIfElse+00525851                                                                                                                  
[ 64] 0x00007ff974c4ca14 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_lxe.dll+02935316 MathWorks::lxe::LXEConstants::IsY+00012980                                                                                                                       
[ 65] 0x00007ff974c49e61 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_lxe.dll+02924129 MathWorks::lxe::LXEConstants::IsY+00001793                                                                                                                       
[ 66] 0x00007ff974c4db55 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_lxe.dll+02939733 MathWorks::lxe::LXEConstants::IsY+00017397                                                                                                                       
[ 67] 0x00007ff974c4de03 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_lxe.dll+02940419 MathWorks::lxe::LXEConstants::IsY+00018083                                                                                                                       
[ 68] 0x00007ff974c4d758 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_lxe.dll+02938712 MathWorks::lxe::LXEConstants::IsY+00016376                                                                                                                       
[ 69] 0x00007ff974c49606 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_lxe.dll+02921990 MathWorks::lxe::LxeTypes::GetTypeXvalueOf+00000598                                                                                                               
[ 70] 0x00007ff974d17303 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_lxe.dll+03764995 MathWorks::lxe::SetEngineImplUnlinkFlagForAllCallsOnStack+00042979                                                                                               
[ 71] 0x00007ff974d1ae10 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_lxe.dll+03780112 MathWorks::lxe::SetEngineImplUnlinkFlagForAllCallsOnStack+00058096                                                                                               
[ 72] 0x00007ff979b74a90 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\libmwlxemainservices.dll+01198736 FeatureTestObservableWorkspace+00184240                                                                                                           
[ 73] 0x00007ff979a997db C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\libmwlxemainservices.dll+00301019 mwboost::archive::codecvt_null<wchar_t>::do_max_length+00204891                                                                                   
[ 74] 0x00007ff979a99b25 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\libmwlxemainservices.dll+00301861 mwboost::archive::codecvt_null<wchar_t>::do_max_length+00205733                                                                                   
[ 75] 0x00007ff979a99495 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\libmwlxemainservices.dll+00300181 mwboost::archive::codecvt_null<wchar_t>::do_max_length+00204053                                                                                   
[ 76] 0x00007ff979a9bad8 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\libmwlxemainservices.dll+00309976 mwboost::archive::codecvt_null<wchar_t>::do_max_length+00213848                                                                                   
[ 77] 0x00007ff979d9da32 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_dispatcher.dll+01038898 Mfh_file::dispatch_file_common+00000178                                                                                                                   
[ 78] 0x00007ff979d9c9e8 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_dispatcher.dll+01034728 Mfh_error::lookup+00011928                                                                                                                                
[ 79] 0x00007ff979d9daed C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_dispatcher.dll+01039085 Mfh_file::dispatch_with_reuse+00000045                                                                                                                    
[ 80] 0x00007ff974f1f5c0 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_lxe.dll+05895616 MathWorks::lxe::CreateUnboundFunctionHandle+00010688                                                                                                             
[ 81] 0x00007ff979ae0dad C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\libmwlxemainservices.dll+00593325 mwboost::archive::detail::pointer_oserializer<mwboost::archive::xml_oarchive,MathWorks::lxe::PreLineExecutionEvent>::save_object_ptr+00078989     
[ 82] 0x00007ff979ae0ebb C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\libmwlxemainservices.dll+00593595 mwboost::archive::detail::pointer_oserializer<mwboost::archive::xml_oarchive,MathWorks::lxe::PreLineExecutionEvent>::save_object_ptr+00079259     
[ 83] 0x00007ff979b3f321 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\libmwlxemainservices.dll+00979745 mwboost::archive::detail::iserializer<mwboost::archive::text_iarchive,MathWorks::MatlabComponents::ComponentIdentifier>::load_object_data+00305057
[ 84] 0x00007ff979b3eed9 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\libmwlxemainservices.dll+00978649 mwboost::archive::detail::iserializer<mwboost::archive::text_iarchive,MathWorks::MatlabComponents::ComponentIdentifier>::load_object_data+00303961
[ 85] 0x00007ff979b3f6ec C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\libmwlxemainservices.dll+00980716 mwboost::archive::detail::iserializer<mwboost::archive::text_iarchive,MathWorks::MatlabComponents::ComponentIdentifier>::load_object_data+00306028
[ 86] 0x00007ff97b41c0d3 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\m_interpreter.dll+00573651 inCallFcnWithTrapInDesiredWSAndPublishEvents+00000099                                                                                                    
[ 87] 0x00007ff97a85e922 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\iqm.dll+00715042 iqm::BaseFEvalPlugin::inCallFcnWithTrap+00000066                                                                                                                   
[ 88] 0x00007ff97a85e1f2 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\iqm.dll+00713202 iqm::BaseFEvalPlugin::execute+00000466                                                                                                                             
[ 89] 0x00007ff97a85e002 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\iqm.dll+00712706 iqm::FEvalPlugin<cmddistributor::FEvalIIP>::execute+00000018                                                                                                       
[ 90] 0x00007ff97bde2080 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\mcr.dll+00401536 mcrInstantiationError::operator=+00082192                                                                                                                          
[ 91] 0x00007ff97a848a4c C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\iqm.dll+00625228 iqm::Iqm::setupIqmFcnPtrs+00097324                                                                                                                                 
[ 92] 0x00007ff97a81ade1 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\iqm.dll+00437729 iqm::Iqm::create+00012145                                                                                                                                          
[ 93] 0x00007ff97a81a529 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\iqm.dll+00435497 iqm::Iqm::create+00009913                                                                                                                                          
[ 94] 0x00007ff97bdd06dc C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\mcr.dll+00329436 mcrInstantiationError::operator=+00010092                                                                                                                          
[ 95] 0x00007ff97bdd1105 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\mcr.dll+00332037 mcrInstantiationError::operator=+00012693                                                                                                                          
[ 96] 0x00007ff97bdcea00 C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\mcr.dll+00322048 mcrInstantiationError::operator=+00002704                                                                                                                          
[ 97] 0x00007ffa16c0855a C:\Program Files\MATLAB\MATLAB Runtime\R2022b\bin\win64\mwboost_thread-vc142-mt-x64-1_75.dll+00034138 mwboost::thread::swap+00000074                                                                                                        
[ 98] 0x00007ffa26491bb2                   C:\WINDOWS\System32\ucrtbase.dll+00138162 configthreadlocale+00000146                                                                                                                                                     
[ 99] 0x00007ffa27607614                   C:\WINDOWS\System32\KERNEL32.DLL+00095764 BaseThreadInitThunk+00000020                                                                                                                                                    
[100] 0x00007ffa286e26b1                      C:\WINDOWS\SYSTEM32\ntdll.dll+00337585 RtlUserThreadStart+00000033                                                                                                                                                     
                                                                                                                                                                                                                                                                     
** This crash report has been saved to disk as C:\Users\gingri1\AppData\Local\Temp\matlab_crash_dump.19264-1 **                                                                                                                                                      
                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                     
MATLAB is exiting because of fatal error

**Comment by cselenyi** [comment]
@GinaGriffioen The WAPI issue should be also fixed in the new worker variant, see #33
